# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BSides Jacksonville 2023
email: info@bsidesjax.org
description: >- # this means to ignore newlines until "baseurl:"
  BSides Jax 2023 is an independent BSides event that is put on by dedicated volunteers
twitter_username: BsidesJAX
github_username: username
minimal_mistakes_skin: contrast # color variations default, air, contrast, dark, neon "https://github.com/mmistakes/minimal-mistakes#skins-color-variations"
search: true

# Added items
logo: /assets/images/ICONS_DISCORD_TWITTER.png # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title: BSides JAX # seperate masthead title from the site title
teaser: # /assets/images/500x300.jpg # a fallback teaser image used in the “Related Posts” module, place a graphic in the /assets/images/ directory and add the filename
subtitle: Rising From The Depths # A short tagline that appears below the title in site masthead.

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "ohp3x"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.themachineryofnight.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ohp3x/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ohp3x/"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BSidesJAX"
    - label: "FaceBook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/bsidesjax"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/rcGFSgyKdY"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bsides_jax"
    - label: "Code of Conduct"
      icon: "fab fa-circle-info"
      url: "/codeoc/"      


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/